// This file is auto-generated by @hey-api/openapi-ts

export type UpdaterRunConfigurationRequest = {
    vendor_id: number;
    json_config: string;
    configuration_id: string;
};

export type ShedulerConfigurationDm = {
    id: string;
    vendor_id: number;
    puppteer_configuration: string;
    interval: ShedulerIntervalDto;
};

export type ShedulerCreateConfigurationDto = {
    vendor_id: number;
    puppteer_configuration: string;
    interval: ShedulerIntervalDto;
    enabled: boolean;
    document_name: string;
};

export type ShedulerFilterConfigurationDto = {
    id?: string | null;
    vendor_id?: number | null;
    enabled?: boolean | null;
};

export type ShedulerFilterJobsDto = {
    configuration_id?: string | null;
    status?: ShedulerJobStatuses | null;
};

export type ShedulerHttpValidationError = {
    detail?: Array<ShedulerValidationError>;
};

export type ShedulerIdDm = {
    id: string;
};

/**
 * Пример DTO для представления интервала:
 * - years: "количество лет" (по умолчанию 0)
 * - days: "количество дней" (по умолчанию 0)
 * - time: собственно, время (часы, минуты и секунды)
 */
export type ShedulerIntervalDto = {
    years?: number;
    days?: number;
    time: string;
};

export type ShedulerJobDm = {
    id: string;
    configuration_id: string;
    status?: ShedulerJobStatuses;
};

export type ShedulerJobStatuses = 'BLANK' | 'PENDING' | 'RUNNING' | 'ERROR' | 'SUCCESS';

export type ShedulerValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type CoreBodyCreateParsingConfiguration = {
    file: Blob | File;
    title: string;
    sections: string;
    vendor: string;
};

export type CoreBodyPreprocessFile = {
    file_to_process: Blob | File;
};

export type CoreCreateVendorDto = {
    title: string;
    websiteUrl?: string | null;
    city?: string | null;
};

export type CoreDummyUdateconfiguration = {
    configuration: string;
};

export type CoreHttpValidationError = {
    detail?: Array<CoreValidationError>;
};

export type CoreIdDm = {
    id: number;
};

export type CoreLengthUnits = 'см' | 'мм' | 'м';

export type CoreMeasurmentRangeDto = {
    value: Array<number>;
    units: CoreLengthUnits;
    useFilter?: boolean;
};

export type CoreParsingConfigurationDm = {
    file_url: string;
    configuration: string;
    vendor_id: number;
    price_list_title: string;
};

export type CorePriceList = {
    id: number;
    title?: string | null;
    date_time?: string | null;
    parsed?: boolean | null;
};

export type CoreProductPosition = {
    id: number;
    type?: string | null;
    vendor_title?: string | null;
    steel_mark?: string | null;
    price?: number | null;
    quantity?: number | null;
    sizes?: Array<CoreSizeDto>;
};

export type CoreSearchDto = {
    vendor?: string | null;
    vendor_id?: number | null;
    type?: string | null;
    steel_mark?: string | null;
    width?: CoreMeasurmentRangeDto | null;
    length?: CoreMeasurmentRangeDto | null;
    height?: CoreMeasurmentRangeDto | null;
    thickness?: CoreMeasurmentRangeDto | null;
    diameter?: CoreMeasurmentRangeDto | null;
};

export type CoreSizeDto = {
    id: number;
    field_name: string;
    measurment_unit: string;
    value_range: [
        number,
        number
    ] | string;
    value_range_in_mm: [
        number,
        number
    ] | string;
};

export type CoreValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type CoreVendorAboutDto = {
    id: number;
    title: string;
    unique_document_titles?: Array<string | null> | null;
};

export type ConfigControllerRunConfigurationData = {
    body: UpdaterRunConfigurationRequest;
    path?: never;
    query?: never;
    url: '/updater/config/run_configuration';
};

export type ConfigControllerRunConfigurationResponses = {
    200: unknown;
};

export type DeleteDownloadingConfigurationData = {
    body: ShedulerFilterConfigurationDto;
    path?: never;
    query?: never;
    url: '/sheduler/automation_configurations/';
};

export type DeleteDownloadingConfigurationErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type DeleteDownloadingConfigurationError = DeleteDownloadingConfigurationErrors[keyof DeleteDownloadingConfigurationErrors];

export type DeleteDownloadingConfigurationResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateDownloadingConfigurationData = {
    body: ShedulerCreateConfigurationDto;
    path?: never;
    query?: never;
    url: '/sheduler/automation_configurations/';
};

export type CreateDownloadingConfigurationErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type CreateDownloadingConfigurationError = CreateDownloadingConfigurationErrors[keyof CreateDownloadingConfigurationErrors];

export type CreateDownloadingConfigurationResponses = {
    /**
     * Successful Response
     */
    200: ShedulerIdDm;
};

export type CreateDownloadingConfigurationResponse = CreateDownloadingConfigurationResponses[keyof CreateDownloadingConfigurationResponses];

export type RetrieveDownloadingConfigurationData = {
    body: ShedulerFilterConfigurationDto;
    path?: never;
    query?: never;
    url: '/sheduler/automation_configurations/retrieve';
};

export type RetrieveDownloadingConfigurationErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type RetrieveDownloadingConfigurationError = RetrieveDownloadingConfigurationErrors[keyof RetrieveDownloadingConfigurationErrors];

export type RetrieveDownloadingConfigurationResponses = {
    /**
     * Successful Response
     */
    200: ShedulerConfigurationDm;
};

export type RetrieveDownloadingConfigurationResponse = RetrieveDownloadingConfigurationResponses[keyof RetrieveDownloadingConfigurationResponses];

export type ListDownloadingConfigurationsData = {
    body: ShedulerFilterConfigurationDto;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/sheduler/automation_configurations/filter';
};

export type ListDownloadingConfigurationsErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type ListDownloadingConfigurationsError = ListDownloadingConfigurationsErrors[keyof ListDownloadingConfigurationsErrors];

export type ListDownloadingConfigurationsResponses = {
    /**
     * Successful Response
     */
    200: Array<ShedulerConfigurationDm>;
};

export type ListDownloadingConfigurationsResponse = ListDownloadingConfigurationsResponses[keyof ListDownloadingConfigurationsResponses];

export type ForceRunData = {
    body?: never;
    path?: never;
    query: {
        pk: string;
    };
    url: '/sheduler/automation_configurations/force_run';
};

export type ForceRunErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type ForceRunError = ForceRunErrors[keyof ForceRunErrors];

export type ForceRunResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RetrieveJobData = {
    body: ShedulerFilterJobsDto;
    path?: never;
    query?: never;
    url: '/sheduler/automation_jobs/retrieve';
};

export type RetrieveJobErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type RetrieveJobError = RetrieveJobErrors[keyof RetrieveJobErrors];

export type RetrieveJobResponses = {
    /**
     * Successful Response
     */
    200: ShedulerJobDm;
};

export type RetrieveJobResponse = RetrieveJobResponses[keyof RetrieveJobResponses];

export type ListJobsData = {
    body: ShedulerFilterJobsDto;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/sheduler/automation_jobs/filter';
};

export type ListJobsErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type ListJobsError = ListJobsErrors[keyof ListJobsErrors];

export type ListJobsResponses = {
    /**
     * Successful Response
     */
    200: Array<ShedulerJobDm>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type DeleteJobData = {
    body?: never;
    path?: never;
    query: {
        pk: string;
    };
    url: '/sheduler/automation_jobs/';
};

export type DeleteJobErrors = {
    /**
     * Validation Error
     */
    422: ShedulerHttpValidationError;
};

export type DeleteJobError = DeleteJobErrors[keyof DeleteJobErrors];

export type DeleteJobResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeletePriceListData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/core/parsing_configurations/price_list';
};

export type DeletePriceListErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type DeletePriceListError = DeletePriceListErrors[keyof DeletePriceListErrors];

export type DeletePriceListResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RunParsingData = {
    body?: never;
    path?: never;
    query: {
        price_list_id: number;
    };
    url: '/core/parsing_configurations/run_parsing';
};

export type RunParsingErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type RunParsingError = RunParsingErrors[keyof RunParsingErrors];

export type RunParsingResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FilterPricesListsData = {
    body?: never;
    path?: never;
    query: {
        title: string;
        vendor_id: number;
    };
    url: '/core/parsing_configurations';
};

export type FilterPricesListsErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type FilterPricesListsError = FilterPricesListsErrors[keyof FilterPricesListsErrors];

export type FilterPricesListsResponses = {
    /**
     * Successful Response
     */
    200: Array<CorePriceList>;
};

export type FilterPricesListsResponse = FilterPricesListsResponses[keyof FilterPricesListsResponses];

export type CreateParsingConfigurationData = {
    body: CoreBodyCreateParsingConfiguration;
    path?: never;
    query?: never;
    url: '/core/parsing_configurations';
};

export type CreateParsingConfigurationErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type CreateParsingConfigurationError = CreateParsingConfigurationErrors[keyof CreateParsingConfigurationErrors];

export type CreateParsingConfigurationResponses = {
    /**
     * Successful Response
     */
    200: CoreIdDm;
};

export type CreateParsingConfigurationResponse = CreateParsingConfigurationResponses[keyof CreateParsingConfigurationResponses];

export type PreprocessFileData = {
    body: CoreBodyPreprocessFile;
    path?: never;
    query?: never;
    url: '/core/parsing_configurations/preprocess_file';
};

export type PreprocessFileErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type PreprocessFileError = PreprocessFileErrors[keyof PreprocessFileErrors];

export type PreprocessFileResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type PreprocessFileResponse = PreprocessFileResponses[keyof PreprocessFileResponses];

export type GetParsingConfigurationData = {
    body?: never;
    path?: never;
    query: {
        price_list_id: number;
    };
    url: '/core/parsing_configurations/parsing_configurations';
};

export type GetParsingConfigurationErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type GetParsingConfigurationError = GetParsingConfigurationErrors[keyof GetParsingConfigurationErrors];

export type GetParsingConfigurationResponses = {
    /**
     * Successful Response
     */
    200: CoreParsingConfigurationDm;
};

export type GetParsingConfigurationResponse = GetParsingConfigurationResponses[keyof GetParsingConfigurationResponses];

export type UpdateParsingConfigurationData = {
    body: CoreDummyUdateconfiguration;
    path?: never;
    query: {
        price_list_id: number;
    };
    url: '/core/parsing_configurations/parsing_configurations';
};

export type UpdateParsingConfigurationErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type UpdateParsingConfigurationError = UpdateParsingConfigurationErrors[keyof UpdateParsingConfigurationErrors];

export type UpdateParsingConfigurationResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteVendorData = {
    body?: never;
    path?: never;
    query: {
        id_: number;
    };
    url: '/core/vendors';
};

export type DeleteVendorErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type DeleteVendorError = DeleteVendorErrors[keyof DeleteVendorErrors];

export type DeleteVendorResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchVendorsData = {
    body?: never;
    path?: never;
    query?: {
        substring?: string | null;
        with_unique_documents_titles?: boolean | null;
    };
    url: '/core/vendors';
};

export type SearchVendorsErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type SearchVendorsError = SearchVendorsErrors[keyof SearchVendorsErrors];

export type SearchVendorsResponses = {
    /**
     * Successful Response
     */
    200: Array<CoreVendorAboutDto>;
};

export type SearchVendorsResponse = SearchVendorsResponses[keyof SearchVendorsResponses];

export type CreateVendorData = {
    body: CoreCreateVendorDto;
    path?: never;
    query?: never;
    url: '/core/vendors';
};

export type CreateVendorErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type CreateVendorError = CreateVendorErrors[keyof CreateVendorErrors];

export type CreateVendorResponses = {
    /**
     * Successful Response
     */
    200: CoreVendorAboutDto;
};

export type CreateVendorResponse = CreateVendorResponses[keyof CreateVendorResponses];

export type CitySearchData = {
    body?: never;
    path?: never;
    query: {
        substring: string;
    };
    url: '/core/cities/search';
};

export type CitySearchErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type CitySearchError = CitySearchErrors[keyof CitySearchErrors];

export type CitySearchResponses = {
    /**
     * Successful Response
     */
    200: Array<CoreProductPosition>;
};

export type CitySearchResponse = CitySearchResponses[keyof CitySearchResponses];

export type SearchData = {
    body: CoreSearchDto;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/core/positions/search';
};

export type SearchErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * Successful Response
     */
    200: Array<CoreProductPosition>;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type SearchPositionsData = {
    body: CoreSearchDto;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/core/positions/search_positions';
};

export type SearchPositionsErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type SearchPositionsError = SearchPositionsErrors[keyof SearchPositionsErrors];

export type SearchPositionsResponses = {
    /**
     * Successful Response
     */
    200: Array<CoreProductPosition>;
};

export type SearchPositionsResponse = SearchPositionsResponses[keyof SearchPositionsResponses];

export type FilterByPropertyValueData = {
    body?: never;
    path?: never;
    query: {
        propery_type: string;
        substring: string;
    };
    url: '/core/positions/filter_by_property_value';
};

export type FilterByPropertyValueErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type FilterByPropertyValueError = FilterByPropertyValueErrors[keyof FilterByPropertyValueErrors];

export type FilterByPropertyValueResponses = {
    /**
     * Successful Response
     */
    200: Array<string>;
};

export type FilterByPropertyValueResponse = FilterByPropertyValueResponses[keyof FilterByPropertyValueResponses];

export type MeasurmentsData = {
    body?: never;
    path?: never;
    query: {
        vendor_position_measurment_field_name: string;
    };
    url: '/core/measurments/get_measurment_range_min_max_values';
};

export type MeasurmentsErrors = {
    /**
     * Validation Error
     */
    422: CoreHttpValidationError;
};

export type MeasurmentsError = MeasurmentsErrors[keyof MeasurmentsErrors];

export type MeasurmentsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};