// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, formDataBodySerializer } from '@hey-api/client-axios';
import type { ConfigControllerRunConfigurationData, DeleteDownloadingConfigurationData, DeleteDownloadingConfigurationError, CreateDownloadingConfigurationData, CreateDownloadingConfigurationResponse, CreateDownloadingConfigurationError, RetrieveDownloadingConfigurationData, RetrieveDownloadingConfigurationResponse, RetrieveDownloadingConfigurationError, ListDownloadingConfigurationsData, ListDownloadingConfigurationsResponse, ListDownloadingConfigurationsError, ForceRunData, ForceRunError, RetrieveJobData, RetrieveJobResponse, RetrieveJobError, ListJobsData, ListJobsResponse, ListJobsError, DeleteJobData, DeleteJobError, DeletePriceListData, DeletePriceListError, RunParsingData, RunParsingError, FilterPricesListsData, FilterPricesListsResponse, FilterPricesListsError, CreateParsingConfigurationData, CreateParsingConfigurationResponse, CreateParsingConfigurationError, PreprocessFileData, PreprocessFileResponse, PreprocessFileError, GetParsingConfigurationData, GetParsingConfigurationResponse, GetParsingConfigurationError, UpdateParsingConfigurationData, UpdateParsingConfigurationError, DeleteVendorData, DeleteVendorError, SearchVendorsData, SearchVendorsResponse, SearchVendorsError, CreateVendorData, CreateVendorResponse, CreateVendorError, CitySearchData, CitySearchResponse, CitySearchError, SearchData, SearchResponse, SearchError, SearchPositionsData, SearchPositionsResponse, SearchPositionsError, FilterByPropertyValueData, FilterByPropertyValueResponse, FilterByPropertyValueError, MeasurmentsData, MeasurmentsError } from './types.gen';

export const client = createClient(createConfig());

export const configControllerRunConfiguration = <ThrowOnError extends boolean = false>(options: Options<ConfigControllerRunConfigurationData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
        url: '/updater/config/run_configuration',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete
 * Удаляет конфигурации по заданному фильтру.
 * Если нужно удалять только одну конфигурацию — используйте data.id.
 */
export const deleteDownloadingConfiguration = <ThrowOnError extends boolean = false>(options: Options<DeleteDownloadingConfigurationData, ThrowOnError>) => {
    return (options?.client ?? client).delete<unknown, DeleteDownloadingConfigurationError, ThrowOnError>({
        url: '/sheduler/automation_configurations/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Create
 * Создаёт новую конфигурацию и возвращает её идентификатор.
 */
export const createDownloadingConfiguration = <ThrowOnError extends boolean = false>(options: Options<CreateDownloadingConfigurationData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateDownloadingConfigurationResponse, CreateDownloadingConfigurationError, ThrowOnError>({
        url: '/sheduler/automation_configurations/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Retrieve
 * Возвращает одну конфигурацию по фильтру.
 * Для примера: если указан data.id — ищем только по нему.
 * Можно расширить фильтр по любым полям FilterConfigurationDTO.
 */
export const retrieveDownloadingConfiguration = <ThrowOnError extends boolean = false>(options: Options<RetrieveDownloadingConfigurationData, ThrowOnError>) => {
    return (options?.client ?? client).post<RetrieveDownloadingConfigurationResponse, RetrieveDownloadingConfigurationError, ThrowOnError>({
        url: '/sheduler/automation_configurations/retrieve',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * List
 * Возвращает список конфигураций по фильтру.
 * Аналогично можно расширять фильтрацию.
 */
export const listDownloadingConfigurations = <ThrowOnError extends boolean = false>(options: Options<ListDownloadingConfigurationsData, ThrowOnError>) => {
    return (options?.client ?? client).post<ListDownloadingConfigurationsResponse, ListDownloadingConfigurationsError, ThrowOnError>({
        url: '/sheduler/automation_configurations/filter',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Force Run
 */
export const forceRun = <ThrowOnError extends boolean = false>(options: Options<ForceRunData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, ForceRunError, ThrowOnError>({
        url: '/sheduler/automation_configurations/force_run',
        ...options
    });
};

/**
 * Retrieve
 * Получаем одно задание по фильтру (например, по id).
 */
export const retrieveJob = <ThrowOnError extends boolean = false>(options: Options<RetrieveJobData, ThrowOnError>) => {
    return (options?.client ?? client).post<RetrieveJobResponse, RetrieveJobError, ThrowOnError>({
        url: '/sheduler/automation_jobs/retrieve',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Filter
 * Возвращаем список задач по фильтру.
 */
export const listJobs = <ThrowOnError extends boolean = false>(options: Options<ListJobsData, ThrowOnError>) => {
    return (options?.client ?? client).post<ListJobsResponse, ListJobsError, ThrowOnError>({
        url: '/sheduler/automation_jobs/filter',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete
 * Удаляем задачу по её первичному ключу (id).
 */
export const deleteJob = <ThrowOnError extends boolean = false>(options: Options<DeleteJobData, ThrowOnError>) => {
    return (options?.client ?? client).delete<unknown, DeleteJobError, ThrowOnError>({
        url: '/sheduler/automation_jobs/',
        ...options
    });
};

/**
 * Delete Price List
 */
export const deletePriceList = <ThrowOnError extends boolean = false>(options: Options<DeletePriceListData, ThrowOnError>) => {
    return (options?.client ?? client).delete<unknown, DeletePriceListError, ThrowOnError>({
        url: '/core/parsing_configurations/price_list',
        ...options
    });
};

/**
 * Parse Prices List
 * запускает парсинг прайс листа по конфигурации, которая для него определена
 */
export const runParsing = <ThrowOnError extends boolean = false>(options: Options<RunParsingData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, RunParsingError, ThrowOnError>({
        url: '/core/parsing_configurations/run_parsing',
        ...options
    });
};

/**
 * Get Prices Lists
 */
export const filterPricesLists = <ThrowOnError extends boolean = false>(options: Options<FilterPricesListsData, ThrowOnError>) => {
    return (options?.client ?? client).get<FilterPricesListsResponse, FilterPricesListsError, ThrowOnError>({
        url: '/core/parsing_configurations',
        ...options
    });
};

/**
 * Create Parsing Configuration
 */
export const createParsingConfiguration = <ThrowOnError extends boolean = false>(options: Options<CreateParsingConfigurationData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateParsingConfigurationResponse, CreateParsingConfigurationError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/core/parsing_configurations',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Preprocess File
 */
export const preprocessFile = <ThrowOnError extends boolean = false>(options: Options<PreprocessFileData, ThrowOnError>) => {
    return (options?.client ?? client).post<PreprocessFileResponse, PreprocessFileError, ThrowOnError>({
        ...formDataBodySerializer,
        responseType: 'blob',
        url: '/core/parsing_configurations/preprocess_file',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get Parsing Configuration
 */
export const getParsingConfiguration = <ThrowOnError extends boolean = false>(options: Options<GetParsingConfigurationData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetParsingConfigurationResponse, GetParsingConfigurationError, ThrowOnError>({
        url: '/core/parsing_configurations/parsing_configurations',
        ...options
    });
};

/**
 * Update Parsing Configuration
 */
export const updateParsingConfiguration = <ThrowOnError extends boolean = false>(options: Options<UpdateParsingConfigurationData, ThrowOnError>) => {
    return (options?.client ?? client).patch<unknown, UpdateParsingConfigurationError, ThrowOnError>({
        url: '/core/parsing_configurations/parsing_configurations',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Vendor
 */
export const deleteVendor = <ThrowOnError extends boolean = false>(options: Options<DeleteVendorData, ThrowOnError>) => {
    return (options?.client ?? client).delete<unknown, DeleteVendorError, ThrowOnError>({
        url: '/core/vendors',
        ...options
    });
};

/**
 * Get Vendors
 */
export const searchVendors = <ThrowOnError extends boolean = false>(options?: Options<SearchVendorsData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchVendorsResponse, SearchVendorsError, ThrowOnError>({
        url: '/core/vendors',
        ...options
    });
};

/**
 * Create Vendor
 */
export const createVendor = <ThrowOnError extends boolean = false>(options: Options<CreateVendorData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateVendorResponse, CreateVendorError, ThrowOnError>({
        url: '/core/vendors',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Search
 */
export const citySearch = <ThrowOnError extends boolean = false>(options: Options<CitySearchData, ThrowOnError>) => {
    return (options?.client ?? client).get<CitySearchResponse, CitySearchError, ThrowOnError>({
        url: '/core/cities/search',
        ...options
    });
};

/**
 * Search
 */
export const search = <ThrowOnError extends boolean = false>(options: Options<SearchData, ThrowOnError>) => {
    return (options?.client ?? client).post<SearchResponse, SearchError, ThrowOnError>({
        url: '/core/positions/search',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Search Positions
 */
export const searchPositions = <ThrowOnError extends boolean = false>(options: Options<SearchPositionsData, ThrowOnError>) => {
    return (options?.client ?? client).post<SearchPositionsResponse, SearchPositionsError, ThrowOnError>({
        url: '/core/positions/search_positions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Filter By Property Value
 */
export const filterByPropertyValue = <ThrowOnError extends boolean = false>(options: Options<FilterByPropertyValueData, ThrowOnError>) => {
    return (options?.client ?? client).get<FilterByPropertyValueResponse, FilterByPropertyValueError, ThrowOnError>({
        url: '/core/positions/filter_by_property_value',
        ...options
    });
};

/**
 * Get Measurment Range Min Max Values
 */
export const measurments = <ThrowOnError extends boolean = false>(options: Options<MeasurmentsData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, MeasurmentsError, ThrowOnError>({
        url: '/core/measurments/get_measurment_range_min_max_values',
        ...options
    });
};